### ISSUE TITLE
Please make your project compile with -w "+compatibility-notation"

### ISSUE THREAD

**Issue by Zimmi48** [mit-plv/cross-crypto#9]
Please make your project compile with `-w "+compatibility-notation"` to prepare for the Coq 8.9 release. We would appreciate if this could be done ASAP. If you have trouble doing so, please raise your concern at coq/coq#8383.

**Comment by Zimmi48** [comment]
As noted by @JasonGross, this seems to actually stem from https://github.com/adampetcher/fcf.

**Comment by andres-erbsen** [comment]
I don't understand what there is to be done. If I add `-arg "-w +compatibility-notation"` to `_CoqProject`, a clean build completes without errors. https://gist.github.com/andres-erbsen/cdb15dbda86ccdc99c8878cf0187ebfd

**Comment by Zimmi48** [comment]
In our CI logs, I get:

```
File "./src/FCF/Lognat.v", line 36, characters 21-26:
Warning: Psucc is Pos.succ [compatibility-notation,deprecated]
File "./src/FCF/Lognat.v", line 43, characters 9-14:
Warning: Psucc is Pos.succ [compatibility-notation,deprecated]
File "./src/FCF/Lognat.v", line 63, characters 24-29:
Warning: Psucc is Pos.succ [compatibility-notation,deprecated]
```

That's all. That being said, it appears to have been fixed in https://github.com/adampetcher/fcf/pull/21/files#diff-21ba8177aacbd2238d763edd93c1c0eb, so all that remains to do is to update the submodule :tada: 

I don't know why you didn't get these errors while compiling. Maybe it is your setup, or maybe it is a coq_makefile bug.
